version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: my-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: testug
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network

volumes:
  mongo_data:

networks:
  mongo-network:
